### PR TITLE
Fixes #44 Another duplicate free during SendMsg error

### LINKED ISSUE #44: Another duplicate free during SendMsg error
While running tests I was still getting intermittent duplicate frees. I modified
`message.Free()` to save the stack trace of the goroutine that executed it. That
way when a duplicate free is detected I can print the stack of the previous free
call. Sure enough there is another dup free during error what was not fixed in
271babf6f292a7800626b358867cc33efc007d21. I have a PR incoming.

```diff
diff --git a/message.go b/message.go
index 2ae59a5..49352de 100644
--- a/message.go
+++ b/message.go
@@ -15,6 +15,8 @@
 package mangos

 import (
+	"fmt"
+	"runtime"
 	"sync/atomic"
 )

@@ -30,6 +32,7 @@ type Message struct {
 	hbuf   []byte
 	bsize  int
 	refcnt int32
+	LastStack []byte
 }

 type msgCacheInfo struct {
@@ -56,6 +59,10 @@ func (m *Message) Free() {
 	if v := atomic.AddInt32(&m.refcnt, -1); v > 0 {
 		return
 	}
+	if li := atomic.LoadInt32(&m.refcnt); li < 0 {
+		panic(fmt.Sprintf("msg refcnt (%d) should never be < 0, double free occurred\n===BEGIN STACK:\n%s\n===END STACK\n", li, m.LastStack));
+	}
+	runtime.Stack(m.LastStack, false)
 	for i := range messageCache {
 		if m.bsize == messageCache[i].maxbody {
 			ch = messageCache[i].cache
@@ -99,6 +106,7 @@ func NewMessage(sz int) *Message {
 		m.bbuf = make([]byte, 0, sz)
 		m.hbuf = make([]byte, 0, 32)
 		m.bsize = sz
+		m.LastStack = make([]byte, 4096)
 	}

m.refcnt = 1
```

And the output:

    rpz@ubuntu:~/gowrk/src/github.com/gdamore/mangos/test$ ~/repeat.sh 10 device_test.go common_test.go tls_test.go
    error SendMsg: use of closed network connection
    panic: msg refcnt (-1) should never be < 0, double free occurred
    ===BEGIN STACK:
    goroutine 74 [running]:
    github.com/gdamore/mangos.(*Message).Free(0xc2080fe090)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/message.go:65 +0x2bb
    github.com/gdamore/mangos.(*connipc).Send(0xc20810a000, 0xc2080fe090, 0x7f04f5a0e8c0, 0xc20800a450)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/conn.go:167 +0x236
    github.com/gdamore/mangos.(*pipe).SendMsg(0xc20813e100, 0xc2080fe090, 0x0, 0x0)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/pipe.go:91 +0x7c
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2081420c0, 0x7f04f5a1add0, 0xc20813e100)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:47 +0x15c
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:79 +0x13b

    ===END STACK

    goroutine 74 [running]:
    github.com/gdamore/mangos.(*Message).Free(0xc2080fe090)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/message.go:63 +0x263
    github.com/gdamore/mangos/protocol/pair.(*pair).sender(0xc2081420c0, 0x7f04f5a1add0, 0xc20813e100)
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:49 +0x27c
    created by github.com/gdamore/mangos/protocol/pair.(*pair).AddEndpoint
        /home/rpz/gowrk/src/github.com/gdamore/mangos/protocol/pair/pair.go:79 +0x13b

### PR DESCRIPTION
**Pull request by rzezeski**
Fixes #44.

### CODE REVIEW

File: conn.go [hunk 1]
```diff
@@ -160,7 +160,6 @@ func (p *connipc) Send(msg *Message) error {
 	// prevent interleaved writes
 	p.wlock.Lock()
 	defer p.wlock.Unlock()
-	defer msg.Free()
```
Comment (gdamore) [inline conn.go]: Good catch.

**Comment by tylertreat** [comment]
Nice :)
